version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_anketa
    ports:
      - 3308:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anketa
      MYSQL_USER: user
      MYSQL_PASSWORD: user